import { Link, useNavigate, useParams } from 'react-router-dom';
import { Pencil } from 'lucide-react';
import { EntityDetailShell } from '../../components/DetailPage/EntityDetailShell';
import { DetailField, DetailGrid } from '../../components/DetailPage/DetailField';
import { Button } from '../../components/Button/Button';
import { Card, CardHeader, StatCard } from '../../components/ui/Card';
import { useAuth } from '../../hooks/useAuth';
import { useEntityDetail } from '../../hooks/useEntityDetail';
import { firestoreService } from '../../services/firestore';
import { TaxMode, TaxType } from '../../types';
import {
  formatExpenseTaxLabel,
  getExpenseInputTax,
} from '../../utils/expenseHelpers';
import { formatMoney } from '../../utils/profit';
import { formatDateLocal } from '../../utils/date';
import { getExpenseVendorDisplay } from '../../utils/vendorHelpers';

function taxModeLabel(mode: TaxMode | undefined): string {
  if (mode === TaxMode.INCLUSIVE) return 'Inclusive';
  if (mode === TaxMode.EXCLUSIVE) return 'Exclusive';
  return '—';
}

export function ExpenseDetailPage() {
  const { expenseId } = useParams<{ expenseId: string }>();
  const navigate = useNavigate();
  const { company } = useAuth();
  const currency = company?.currency ?? 'AED';

  const { entity: expense, loading, notFound } = useEntityDetail({
    id: expenseId,
    fetch: firestoreService.expenses.get,
    errorMessage: 'Failed to load expense',
  });

  const inputTax = expense ? getExpenseInputTax(expense) : 0;
  const tracksTax = expense?.taxType != null && expense.taxType !== TaxType.NONE;

  return (
    <EntityDetailShell
      loading={loading}
      loadingLabel="Loading expense…"
      notFound={notFound}
      notFoundTitle="Expense not found"
      notFoundDescription="This expense may have been deleted."
      backTo="/expenses"
      backLabel="Back to expenses"
      title={expense?.description ?? 'Expense'}
      description={expense ? expense.category : undefined}
      actions={
        expense ? (
          <Button
            type="button"
            variant="outline"
            size="sm"
            onClick={() => navigate(`/expenses/${expense.id}/edit`)}
          >
            <Pencil className="w-4 h-4" />
            Edit
          </Button>
        ) : null
      }
    >
      {expense && (
        <>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
            <StatCard label="Amount" value={formatMoney(expense.amount, currency)} />
            <StatCard
              label="Input tax"
              value={inputTax > 0 ? formatMoney(inputTax, currency) : '—'}
            />
          </div>

          <Card>
            <CardHeader title="Expense details" />
            <DetailGrid columns={3}>
              <DetailField label="Date" value={formatDateLocal(expense.expenseDate)} />
              <DetailField label="Category" value={expense.category} />
              <DetailField label="Description" value={expense.description} />
              <DetailField label="Reference" value={expense.reference} />
              <DetailField
                label="Vendor"
                value={
                  expense.vendorId ? (
                    <Link
                      to={`/vendors/${expense.vendorId}`}
                      className="text-indigo-600 dark:text-indigo-400 hover:underline"
                    >
                      {getExpenseVendorDisplay(expense)}
                    </Link>
                  ) : (
                    getExpenseVendorDisplay(expense)
                  )
                }
              />
              <DetailField label="Amount" value={formatMoney(expense.amount, currency)} />
              {expense.saleId ? (
                <DetailField
                  label="Linked sale"
                  value={
                    <Link
                      to={`/sales/${expense.saleId}`}
                      className="text-indigo-600 dark:text-indigo-400 hover:underline"
                    >
                      {expense.reference ? `Order ${expense.reference}` : 'View order'}
                    </Link>
                  }
                />
              ) : null}
              {expense.autoGenerated ? (
                <DetailField
                  label="Source"
                  value="Auto-generated from sale"
                />
              ) : null}
            </DetailGrid>
            {expense.notes && (
              <div className="mt-4 pt-4 border-t border-gray-200 dark:border-gray-700">
                <DetailField label="Notes" value={expense.notes} />
              </div>
            )}
          </Card>

          {tracksTax && (
            <Card>
              <CardHeader title="Input tax (ITC)" />
              <DetailGrid columns={3}>
                <DetailField label="Tax type" value={formatExpenseTaxLabel(expense.taxType)} />
                <DetailField label="Tax %" value={`${expense.taxPercentage ?? 0}%`} />
                <DetailField label="Tax mode" value={taxModeLabel(expense.taxMode)} />
                <DetailField label="Tax amount" value={formatMoney(inputTax, currency)} />
              </DetailGrid>
            </Card>
          )}
        </>
      )}
    </EntityDetailShell>
  );
}
