import { useEffect, useMemo, useState } from 'react';
import { Link, useNavigate, useSearchParams } from 'react-router-dom';
import { Eye, Pencil, Plus, Receipt, Trash2, Wallet } from 'lucide-react';
import { SectionPage } from '../../components/SectionPage/SectionPage';
import { Button } from '../../components/Button/Button';
import { Card, StatCard } from '../../components/ui/Card';
import { ListToolbar } from '../../components/ui/ListToolbar';
import { EmptyState } from '../../components/ui/EmptyState';
import { LoadingView } from '../../components/AppLoader/AppLoader';
import { FilterSelect } from '../../components/ui/FilterSelect';
import { DataTable, type DataTableColumn } from '../../components/ui/DataTable';
import { useModuleAccess } from '../../hooks/usePermissions';
import { AppModule } from '../../constants/permissions';
import { useAuth } from '../../hooks/useAuth';
import { useNotification } from '../../hooks/useNotification';
import { notDeleted, useEntityList } from '../../hooks/useEntityList';
import { EXPENSE_CATEGORIES } from '../../constants/expenseCategories';
import { firestoreService } from '../../services/firestore';
import type { Expense } from '../../types';
import { formatDateLocal } from '../../utils/date';
import {
  dateFilterRange,
  formatExpenseTaxLabel,
  getExpenseInputTax,
  isDateInRange,
  type DateFilter,
} from '../../utils/expenseHelpers';
import { formatMoney } from '../../utils/profit';
import { getExpenseVendorDisplay, vendorFilterOptions } from '../../utils/vendorHelpers';

export function Expenses() {
  const navigate = useNavigate();
  const { canCreate, canUpdate, canDelete } = useModuleAccess(AppModule.EXPENSES);
  const { company, user } = useAuth();
  const notification = useNotification();
  const currency = company?.currency ?? 'AED';
  const [searchParams, setSearchParams] = useSearchParams();

  const [search, setSearch] = useState('');
  const [dateFilter, setDateFilter] = useState<DateFilter>('30d');
  const [categoryFilter, setCategoryFilter] = useState('');
  const [vendorFilter, setVendorFilter] = useState(() => searchParams.get('vendor') ?? '');

  const emptyData = useMemo(() => [] as Expense[], []);

  const { data: expenses, loading, reload } = useEntityList({
    initialData: emptyData,
    errorMessage: 'Failed to load expenses',
    fetch: async (companyId) => {
      const list = await firestoreService.expenses.getAll(companyId);
      return list.filter(notDeleted);
    },
  });

  const vendorOptions = useMemo(
    () =>
      vendorFilterOptions(expenses, getExpenseVendorDisplay, vendorFilter || undefined),
    [expenses, vendorFilter]
  );

  useEffect(() => {
    const vendorFromUrl = searchParams.get('vendor') ?? '';
    setVendorFilter(vendorFromUrl);
  }, [searchParams]);

  const filtered = useMemo(() => {
    const q = search.trim().toLowerCase();
    const { from, to } = dateFilterRange(dateFilter);

    return expenses.filter((e) => {
      if (!isDateInRange(e.expenseDate, from, to)) return false;
      if (categoryFilter && e.category !== categoryFilter) return false;
      if (vendorFilter && e.vendorId !== vendorFilter) return false;
      if (!q) return true;
      const vendorDisplay = getExpenseVendorDisplay(e);
      return (
        e.description.toLowerCase().includes(q) ||
        e.category.toLowerCase().includes(q) ||
        (e.expenseNumber?.toLowerCase().includes(q) ?? false) ||
        (vendorDisplay?.toLowerCase().includes(q) ?? false) ||
        (e.reference?.toLowerCase().includes(q) ?? false)
      );
    });
  }, [expenses, search, dateFilter, categoryFilter, vendorFilter]);

  const summary = useMemo(() => {
    return filtered.reduce(
      (acc, e) => ({
        count: acc.count + 1,
        total: acc.total + e.amount,
        inputTax: acc.inputTax + getExpenseInputTax(e),
      }),
      { count: 0, total: 0, inputTax: 0 }
    );
  }, [filtered]);

  const openCreate = () => {
    const vendor = searchParams.get('vendor');
    navigate(vendor ? `/expenses/new?vendor=${vendor}` : '/expenses/new');
  };

  const openView = (expense: Expense) => navigate(`/expenses/${expense.id}`);
  const openEdit = (expense: Expense) => navigate(`/expenses/${expense.id}/edit`);

  const handleDelete = (expense: Expense) => {
    if (!company) return;
    if (expense.autoGenerated) {
      notification.error(
        'This expense is managed automatically by its linked sale or purchase order and cannot be deleted here.'
      );
      return;
    }
    notification.confirm({
      title: 'Delete expense?',
      message: `Remove "${expense.description}" (${formatMoney(expense.amount, currency)})? This cannot be undone.`,
      confirmLabel: 'Delete',
      variant: 'danger',
      onConfirm: async () => {
        try {
          await firestoreService.expenses.delete(company.id, expense.id, user!.uid);
          notification.success('Expense deleted');
          reload();
        } catch (err) {
          console.error(err);
          notification.error('Failed to delete expense');
        }
      },
    });
  };

  const columns = useMemo<DataTableColumn<Expense>[]>(
    () => [
      {
        key: 'date',
        header: 'Date',
        sortable: true,
        sortValue: (expense) => expense.expenseDate,
        className: 'text-gray-700 dark:text-gray-300',
        render: (expense) => formatDateLocal(expense.expenseDate),
      },
      {
        key: 'number',
        header: 'Number',
        sortable: true,
        sortValue: (expense) => expense.expenseNumber ?? '',
        className: 'font-mono text-xs text-gray-600 dark:text-gray-400',
        render: (expense) => expense.expenseNumber ?? '—',
      },
      {
        key: 'category',
        header: 'Category',
        sortable: true,
        sortValue: (expense) => expense.category,
        render: (expense) => (
          <span className="inline-flex text-xs px-2 py-0.5 rounded-full bg-gray-100 dark:bg-gray-700 text-gray-700 dark:text-gray-300">
            {expense.category}
          </span>
        ),
      },
      {
        key: 'description',
        header: 'Description',
        sortable: true,
        sortValue: (expense) => expense.description,
        truncate: true,
        className: 'text-gray-900 dark:text-white',
        render: (expense) => (
          <Link
            to={`/expenses/${expense.id}`}
            className="hover:text-indigo-600 dark:hover:text-indigo-400 hover:underline"
          >
            {expense.description}
          </Link>
        ),
      },
      {
        key: 'reference',
        header: 'Reference',
        sortable: true,
        sortValue: (expense) => expense.reference ?? '',
        truncate: true,
        className: 'text-gray-600 dark:text-gray-400',
        render: (expense) => expense.reference ?? '—',
      },
      {
        key: 'vendor',
        header: 'Vendor',
        sortable: true,
        sortValue: (expense) => getExpenseVendorDisplay(expense) ?? '',
        truncate: true,
        className: 'text-gray-600 dark:text-gray-400',
        render: (expense) => getExpenseVendorDisplay(expense) ?? '—',
      },
      {
        key: 'amount',
        header: 'Amount',
        align: 'right',
        sortable: true,
        sortValue: (expense) => expense.amount,
        className: 'font-medium text-gray-900 dark:text-white',
        render: (expense) => formatMoney(expense.amount, currency),
      },
      {
        key: 'inputTax',
        header: 'Input tax',
        align: 'right',
        sortable: true,
        sortValue: (expense) => getExpenseInputTax(expense),
        className: 'text-gray-600 dark:text-gray-400',
        render: (expense) => {
          const tax = getExpenseInputTax(expense);
          return tax > 0 ? formatMoney(tax, currency) : '—';
        },
      },
      {
        key: 'actions',
        header: 'Actions',
        align: 'right',
        render: (expense) => (
          <div className="flex items-center justify-end gap-1">
            <button
              type="button"
              onClick={() => openView(expense)}
              className="p-2 rounded-lg text-gray-600 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-700"
              aria-label={`View ${expense.description}`}
            >
              <Eye className="w-4 h-4" />
            </button>
            {canUpdate && !expense.autoGenerated ? (
              <button
                type="button"
                onClick={() => openEdit(expense)}
                className="p-2 rounded-lg text-gray-600 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-700"
                aria-label={`Edit ${expense.description}`}
              >
                <Pencil className="w-4 h-4" />
              </button>
            ) : null}
            {canDelete && !expense.autoGenerated ? (
              <button
                type="button"
                onClick={() => handleDelete(expense)}
                className="p-2 rounded-lg text-red-600 dark:text-red-400 hover:bg-red-50 dark:hover:bg-red-900/20"
                aria-label={`Delete ${expense.description}`}
              >
                <Trash2 className="w-4 h-4" />
              </button>
            ) : null}
          </div>
        ),
      },
    ],
    [currency, canUpdate, canDelete]
  );

  return (
    <SectionPage
      title="Expenses"
      description="Track business costs that aren't tied to a single order — ads, software, storage, salaries, and more."
    >
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
        {[
          { label: 'Expenses', value: String(summary.count), tone: 'indigo' as const, icon: Receipt },
          { label: 'Total spent', value: formatMoney(summary.total, currency), tone: 'rose' as const, icon: Wallet },
          {
            label: 'Input tax',
            value: formatMoney(summary.inputTax, currency),
            subtext: summary.inputTax > 0 ? 'GST/VAT tracked on expenses' : 'Track tax on expenses optionally',
            tone: 'emerald' as const,
            icon: Receipt,
          },
        ].map((stat) => (
          <StatCard
            key={stat.label}
            label={stat.label}
            value={stat.value}
            subtext={stat.subtext ?? 'Filtered results'}
            tone={stat.tone}
            icon={stat.icon}
          />
        ))}
      </div>

      <Card className="space-y-3">
        <ListToolbar
          search={search}
          onSearchChange={setSearch}
          searchPlaceholder="Search description, vendor, reference"
          searchAriaLabel="Search expenses"
          actions={
            canCreate ? (
              <Button variant="primary" onClick={openCreate} className="flex-1 sm:flex-none">
                <Plus className="w-4 h-4" />
                Add expense
              </Button>
            ) : undefined
          }
          filters={
            <>
              <FilterSelect
                value={dateFilter}
                onChange={(e) => setDateFilter(e.target.value as DateFilter)}
                aria-label="Date range"
              >
                <option value="today">Today</option>
                <option value="7d">Last 7 days</option>
                <option value="30d">Last 30 days</option>
                <option value="all">All time</option>
              </FilterSelect>
              <FilterSelect
                value={vendorFilter}
                onChange={(e) => {
                  const value = e.target.value;
                  setVendorFilter(value);
                  if (value) {
                    setSearchParams({ vendor: value });
                  } else {
                    setSearchParams({});
                  }
                }}
                wide
                aria-label="Vendor"
              >
                <option value="">All vendors</option>
                {vendorOptions.map((v) => (
                  <option key={v.id} value={v.id}>
                    {v.name}
                  </option>
                ))}
              </FilterSelect>
              <FilterSelect
                value={categoryFilter}
                onChange={(e) => setCategoryFilter(e.target.value)}
                wide
                aria-label="Category"
              >
                <option value="">All categories</option>
                {EXPENSE_CATEGORIES.map((c) => (
                  <option key={c} value={c}>
                    {c}
                  </option>
                ))}
              </FilterSelect>
            </>
          }
        />

        {loading ? (
          <LoadingView message="Loading expenses…" size="lg" className="py-16" />
        ) : filtered.length === 0 ? (
          <EmptyState
            icon={Receipt}
            title={expenses.length === 0 ? 'No expenses yet' : 'No expenses match your filters'}
            description={
              expenses.length === 0
                ? 'Record ads, software, storage, and other operating costs here.'
                : 'Try a different search, category, or date range.'
            }
            action={
              expenses.length === 0 && canCreate ? (
                <Button variant="primary" onClick={openCreate}>
                  <Plus className="w-4 h-4" />
                  Add first expense
                </Button>
              ) : undefined
            }
          />
        ) : (
          <>
            <DataTable
              columns={columns}
              rows={filtered}
              rowKey={(expense) => expense.id}
              defaultSort={{ key: 'date', direction: 'desc' }}
            />

            <div className="md:hidden space-y-3">
              {filtered.map((expense) => (
                <div
                  key={expense.id}
                  className="rounded-xl border border-gray-200 dark:border-gray-700 p-4 space-y-2"
                >
                  <div className="flex items-start justify-between gap-2">
                    <div className="min-w-0">
                      <p className="font-semibold text-gray-900 dark:text-white truncate">
                        <Link
                          to={`/expenses/${expense.id}`}
                          className="hover:text-indigo-600 dark:hover:text-indigo-400 hover:underline"
                        >
                          {expense.description}
                        </Link>
                      </p>
                      <p className="text-xs text-gray-500 dark:text-gray-400">
                        {formatDateLocal(expense.expenseDate)}
                        {getExpenseVendorDisplay(expense)
                          ? ` · ${getExpenseVendorDisplay(expense)}`
                          : ''}
                      </p>
                    </div>
                    <p className="shrink-0 font-semibold tabular-nums text-gray-900 dark:text-white text-right">
                      {formatMoney(expense.amount, currency)}
                      {getExpenseInputTax(expense) > 0 && (
                        <span className="block text-xs font-normal text-gray-500 dark:text-gray-400">
                          {formatExpenseTaxLabel(expense.taxType)}{' '}
                          {formatMoney(getExpenseInputTax(expense), currency)}
                        </span>
                      )}
                    </p>
                  </div>
                  <span className="inline-flex text-xs px-2 py-0.5 rounded-full bg-gray-100 dark:bg-gray-700 text-gray-700 dark:text-gray-300">
                    {expense.category}
                  </span>
                  {expense.reference && (
                    <p className="text-xs text-gray-500 dark:text-gray-400">Ref: {expense.reference}</p>
                  )}
                  <div className="flex gap-2 pt-1">
                    <Button variant="outline" size="sm" className="flex-1" onClick={() => openView(expense)}>
                      <Eye className="w-4 h-4" />
                      View
                    </Button>
                    {canUpdate && !expense.autoGenerated ? (
                      <Button variant="outline" size="sm" className="flex-1" onClick={() => openEdit(expense)}>
                        <Pencil className="w-4 h-4" />
                        Edit
                      </Button>
                    ) : null}
                    {canDelete && !expense.autoGenerated ? (
                      <Button
                        variant="ghost"
                        size="sm"
                        onClick={() => handleDelete(expense)}
                        className="text-red-600 dark:text-red-400"
                        aria-label="Delete"
                      >
                        <Trash2 className="w-4 h-4" />
                      </Button>
                    ) : null}
                  </div>
                </div>
              ))}
            </div>
          </>
        )}
      </Card>
    </SectionPage>
  );
}
