import { Link, useNavigate, useParams } from 'react-router-dom';
import { Building2, Layers, Pencil, Receipt, Sparkles } from 'lucide-react';
import { EntityDetailShell } from '../../components/DetailPage/EntityDetailShell';
import { DetailField, DetailGrid, detailLinkClass } from '../../components/DetailPage/DetailField';
import { DetailMetaChip, DetailMetaRow, DetailNotes } from '../../components/DetailPage/DetailMeta';
import { DetailSection } from '../../components/DetailPage/DetailSection';
import { DetailStatStrip } from '../../components/DetailPage/DetailStatStrip';
import { Button } from '../../components/Button/Button';
import { useAuth } from '../../hooks/useAuth';
import { useEntityDetail } from '../../hooks/useEntityDetail';
import { firestoreService } from '../../services/firestore';
import { TaxMode, TaxType } from '../../types';
import {
  formatExpenseTaxLabel,
  getExpenseInputTax,
} from '../../utils/expenseHelpers';
import { formatMoney } from '../../utils/profit';
import { formatDateLocal } from '../../utils/date';
import { getExpenseVendorDisplay } from '../../utils/vendorHelpers';

function taxModeLabel(mode: TaxMode | undefined): string {
  if (mode === TaxMode.INCLUSIVE) return 'Inclusive';
  if (mode === TaxMode.EXCLUSIVE) return 'Exclusive';
  return '—';
}

export function ExpenseDetailPage() {
  const { expenseId } = useParams<{ expenseId: string }>();
  const navigate = useNavigate();
  const { company } = useAuth();
  const currency = company?.currency ?? 'AED';

  const { entity: expense, loading, notFound } = useEntityDetail({
    id: expenseId,
    fetch: firestoreService.expenses.get,
    errorMessage: 'Failed to load expense',
  });

  const inputTax = expense ? getExpenseInputTax(expense) : 0;
  const tracksTax = expense?.taxType != null && expense.taxType !== TaxType.NONE;

  return (
    <EntityDetailShell
      loading={loading}
      loadingLabel="Loading expense…"
      loadingIcon={Receipt}
      notFound={notFound}
      notFoundTitle="Expense not found"
      notFoundDescription="This expense may have been deleted."
      backTo="/expenses"
      backLabel="Back to expenses"
      title={expense?.description ?? 'Expense'}
      description={expense ? expense.category : undefined}
      meta={
        expense ? (
          <DetailMetaRow>
            <DetailMetaChip tone="indigo">{expense.category}</DetailMetaChip>
            <DetailMetaChip tone="gray">{formatDateLocal(expense.expenseDate)}</DetailMetaChip>
            {expense.autoGenerated ? (
              <DetailMetaChip tone="amber" icon={<Sparkles className="w-3 h-3" />}>
                Auto from sale
              </DetailMetaChip>
            ) : null}
          </DetailMetaRow>
        ) : undefined
      }
      actions={
        expense && !expense.autoGenerated ? (
          <Button
            type="button"
            variant="outline"
            onClick={() => navigate(`/expenses/${expense.id}/edit`)}
          >
            <Pencil className="w-4 h-4" />
            Edit expense
          </Button>
        ) : null
      }
    >
      {expense && (
        <>
          <DetailStatStrip
            stats={[
              {
                label: 'Amount paid',
                value: formatMoney(expense.amount, currency),
                icon: Receipt,
                tone: 'indigo',
              },
              {
                label: 'Input tax (ITC)',
                value: inputTax > 0 ? formatMoney(inputTax, currency) : '—',
                icon: Layers,
                tone: inputTax > 0 ? 'emerald' : 'slate',
                valueClassName:
                  inputTax > 0 ? 'text-emerald-700 dark:text-emerald-400' : undefined,
              },
            ]}
          />

          <DetailSection
            icon={Receipt}
            iconTone="indigo"
            title="Expense details"
            description="When, what, and how much was paid."
          >
            <DetailGrid columns={3}>
              <DetailField label="Date" value={formatDateLocal(expense.expenseDate)} />
              <DetailField label="Category" value={expense.category} />
              <DetailField label="Description" value={expense.description} />
              <DetailField label="Reference" value={expense.reference} valueClassName="font-mono text-xs" />
              <DetailField
                label="Vendor"
                value={
                  expense.vendorId ? (
                    <Link to={`/vendors/${expense.vendorId}`} className={detailLinkClass}>
                      {getExpenseVendorDisplay(expense)}
                    </Link>
                  ) : (
                    getExpenseVendorDisplay(expense)
                  )
                }
              />
              <DetailField
                label="Amount"
                value={formatMoney(expense.amount, currency)}
                valueClassName="tabular-nums font-semibold"
              />
              {expense.saleId ? (
                <DetailField
                  label="Linked sale"
                  value={
                    <Link to={`/sales/${expense.saleId}`} className={detailLinkClass}>
                      {expense.reference ? `Order ${expense.reference}` : 'View order'}
                    </Link>
                  }
                />
              ) : null}
            </DetailGrid>
            {expense.notes ? <DetailNotes>{expense.notes}</DetailNotes> : null}
          </DetailSection>

          {tracksTax ? (
            <DetailSection
              icon={Layers}
              iconTone="violet"
              title="Input tax (ITC)"
              description="Tax paid on this expense — counts toward input credit in reports."
            >
              <DetailGrid columns={3}>
                <DetailField label="Tax type" value={formatExpenseTaxLabel(expense.taxType)} />
                <DetailField label="Tax %" value={`${expense.taxPercentage ?? 0}%`} />
                <DetailField label="Tax mode" value={taxModeLabel(expense.taxMode)} />
                <DetailField
                  label="Tax amount"
                  value={formatMoney(inputTax, currency)}
                  valueClassName="tabular-nums font-semibold text-emerald-700 dark:text-emerald-400"
                />
              </DetailGrid>
            </DetailSection>
          ) : null}

          {expense.vendorId ? (
            <DetailSection
              icon={Building2}
              iconTone="emerald"
              title="Vendor"
              description="Payee linked to this expense."
              headerAction={
                <Link to={`/vendors/${expense.vendorId}`} className={`text-xs font-medium ${detailLinkClass}`}>
                  View vendor →
                </Link>
              }
            >
              <DetailField
                label="Name"
                value={
                  <Link to={`/vendors/${expense.vendorId}`} className={detailLinkClass}>
                    {getExpenseVendorDisplay(expense)}
                  </Link>
                }
              />
            </DetailSection>
          ) : null}
        </>
      )}
    </EntityDetailShell>
  );
}
