import { firestoreService } from '../services/firestore';
import type { Expense, PurchaseOrder, PurchasePayment } from '../types';
import { allocateNextExpenseNumber } from './documentNumbers';
import { createListingId } from './productDefaults';
import { allocatePurchasePaymentTax, type PurchasePaymentTaxAllocation } from './purchaseHelpers';
import { nowUtc, utcToLocalDateInput } from './firestoreDates';

function roundMoney(value: number): number {
  return Math.round(value * 100) / 100;
}

function expenseFromPayment(
  purchase: PurchaseOrder,
  payment: PurchasePayment,
  expenseNumber: string,
  tax: PurchasePaymentTaxAllocation,
  existing?: Expense
): Expense {
  const now = nowUtc();
  const tracksTax = (tax.taxAmount ?? 0) > 0;

  return {
    id: existing?.id ?? createListingId(),
    companyId: purchase.companyId,
    expenseNumber,
    expenseDate: payment.paymentDate,
    category: 'Inventory Purchase',
    description: `Payment for PO ${purchase.poNumber}${purchase.reference ? ` (ref ${purchase.reference})` : ''}${payment.reference ? ` — ${payment.reference}` : ''}`,
    amount: roundMoney(payment.amount),
    vendorId: purchase.vendorId,
    vendorName: purchase.vendorName,
    reference: purchase.poNumber,
    notes: payment.notes?.trim() || 'Auto-generated from purchase payment',
    taxType: tracksTax ? tax.taxType : undefined,
    taxPercentage: tracksTax ? tax.taxPercentage : undefined,
    taxMode: tracksTax ? tax.taxMode : undefined,
    taxAmount: tracksTax ? tax.taxAmount : undefined,
    purchaseOrderId: purchase.id,
    purchasePaymentId: payment.id,
    autoGenerated: true,
    createdAt: existing?.createdAt ?? now,
    updatedAt: now,
  };
}

/** Create or update expenses for each payment on a purchase order. */
export async function syncPurchaseExpenses(
  companyId: string,
  purchase: PurchaseOrder,
  deletedBy: string
): Promise<PurchaseOrder> {
  const allExpenses = await firestoreService.expenses.getAll(companyId);
  const linked = allExpenses.filter(
    (e) => e.purchaseOrderId === purchase.id && e.autoGenerated && !e.deleted
  );

  const paymentIds = new Set(purchase.payments.map((p) => p.id));
  const updatedPayments: PurchasePayment[] = [];

  for (let index = 0; index < purchase.payments.length; index++) {
    const payment = purchase.payments[index];
    const existing = linked.find((e) => e.purchasePaymentId === payment.id);
    const expenseNumber =
      existing?.expenseNumber ??
      (await allocateNextExpenseNumber(
        companyId,
        utcToLocalDateInput(payment.paymentDate)
      ));
    const tax = allocatePurchasePaymentTax(purchase, purchase.payments, index);
    const expense = expenseFromPayment(purchase, payment, expenseNumber, tax, existing);

    if (existing) {
      await firestoreService.expenses.update(companyId, existing.id, expense, deletedBy);
    } else {
      await firestoreService.expenses.create(companyId, expense, deletedBy);
    }

    updatedPayments.push({ ...payment, expenseId: expense.id });
  }

  for (const expense of linked) {
    if (expense.purchasePaymentId && !paymentIds.has(expense.purchasePaymentId)) {
      await firestoreService.expenses.delete(companyId, expense.id, deletedBy);
    }
  }

  if (
    updatedPayments.length === purchase.payments.length &&
    updatedPayments.every((p, i) => p.expenseId === purchase.payments[i]?.expenseId)
  ) {
    return purchase;
  }

  const updated: PurchaseOrder = {
    ...purchase,
    payments: updatedPayments,
    updatedAt: nowUtc(),
  };

  await firestoreService.purchases.update(
    companyId,
    purchase.id,
    {
      payments: updatedPayments,
      updatedAt: updated.updatedAt,
    },
    deletedBy
  );

  return updated;
}

/** Soft-delete all auto-generated expenses linked to a purchase order. */
export async function deletePurchaseLinkedExpenses(
  companyId: string,
  purchaseOrderId: string,
  deletedBy: string
): Promise<void> {
  const allExpenses = await firestoreService.expenses.getAll(companyId);
  const linked = allExpenses.filter(
    (e) => e.purchaseOrderId === purchaseOrderId && e.autoGenerated && !e.deleted
  );

  await Promise.all(
    linked.map((expense) => firestoreService.expenses.delete(companyId, expense.id, deletedBy))
  );
}
