import type { Expense, PurchaseOrder } from '../types';
import { PurchaseOrderStatus } from '../types';

function roundMoney(value: number): number {
  return Math.round(value * 100) / 100;
}

export interface VendorLedgerEntry {
  id: string;
  date: Date;
  type: 'purchase' | 'payment' | 'expense';
  reference: string;
  description: string;
  debit: number;
  credit: number;
}

export interface VendorLedgerSummary {
  totalPurchases: number;
  totalPaid: number;
  balanceDue: number;
  openOrders: number;
  entries: VendorLedgerEntry[];
}

export function buildVendorLedger(
  vendorId: string,
  purchases: PurchaseOrder[],
  expenses: Expense[]
): VendorLedgerSummary {
  const vendorPurchases = purchases.filter(
    (p) => !p.deleted && p.vendorId === vendorId && p.status !== PurchaseOrderStatus.CANCELLED
  );

  const vendorExpenses = expenses.filter(
    (e) => !e.deleted && e.vendorId === vendorId && !e.autoGenerated
  );

  const entries: VendorLedgerEntry[] = [];

  for (const po of vendorPurchases) {
    entries.push({
      id: `po-${po.id}`,
      date: po.purchaseDate,
      type: 'purchase',
      reference: po.poNumber,
      description: `Purchase order — ${po.lines.length} line${po.lines.length === 1 ? '' : 's'}`,
      debit: po.total,
      credit: 0,
    });

    for (const payment of po.payments) {
      entries.push({
        id: `pay-${payment.id}`,
        date: payment.paymentDate,
        type: 'payment',
        reference: payment.reference ?? po.poNumber,
        description: `Payment for PO ${po.poNumber}`,
        debit: 0,
        credit: payment.amount,
      });
    }
  }

  for (const expense of vendorExpenses) {
    entries.push({
      id: `exp-${expense.id}`,
      date: expense.expenseDate,
      type: 'expense',
      reference: expense.reference ?? expense.category,
      description: expense.description,
      debit: 0,
      credit: expense.amount,
    });
  }

  entries.sort((a, b) => a.date.getTime() - b.date.getTime());

  const totalPurchases = roundMoney(
    vendorPurchases.reduce((s, p) => s + p.total, 0)
  );
  const poPayments = roundMoney(
    vendorPurchases.reduce(
      (s, p) => s + p.payments.reduce((ps, pay) => ps + pay.amount, 0),
      0
    )
  );
  const manualExpenses = roundMoney(
    vendorExpenses.reduce((s, e) => s + e.amount, 0)
  );
  const totalPaid = roundMoney(poPayments + manualExpenses);
  const balanceDue = roundMoney(
    vendorPurchases.reduce((s, p) => s + p.balanceDue, 0)
  );
  const openOrders = vendorPurchases.filter(
    (p) =>
      p.status !== PurchaseOrderStatus.RECEIVED ||
      p.balanceDue > 0
  ).length;

  return {
    totalPurchases,
    totalPaid,
    balanceDue,
    openOrders,
    entries,
  };
}

export function sumPurchasesByVendor(
  purchases: PurchaseOrder[]
): Map<string, { count: number; total: number; balanceDue: number }> {
  const map = new Map<string, { count: number; total: number; balanceDue: number }>();
  for (const p of purchases) {
    if (p.deleted || !p.vendorId || p.status === PurchaseOrderStatus.CANCELLED) continue;
    const prev = map.get(p.vendorId) ?? { count: 0, total: 0, balanceDue: 0 };
    map.set(p.vendorId, {
      count: prev.count + 1,
      total: roundMoney(prev.total + p.total),
      balanceDue: roundMoney(prev.balanceDue + p.balanceDue),
    });
  }
  return map;
}
